### ISSUE TITLE
How to read biom v2 format into metagenomeSeq?

### ISSUE THREAD

**Issue by lfaller** [HCBravoLab/metagenomeSeq#26]
The vignette mentioned a code snippet but the gist page got lost:

"If you need to load a biom-2.0 file, see: https://gist.github.com/nosson/c9cdcb8cf95e7daae468"

Thanks for any advice!
~Lina

**Comment by jnpaulson** [comment]
Hi @lfaller -
Sorry about that. I fixed the comment in there (I changed my username):
Here is a better link: https://gist.github.com/jnpaulson/c9cdcb8cf95e7daae468

Additionally, you can download the new biom-format package:
```
install.packages("devtools") # if not already installed
devtools::install_github("biomformat", "joey711")
library(biomformat)
x = read_biom(/path/to/file)
obj = biom2MRexperiment(x)
```

**Comment by lfaller** [comment]
Great, this worked -- thanks a bunch!
