### ISSUE TITLE
matrixStats::rowMedians() instead of Biobase::rowMedians()

### ISSUE THREAD

**Issue by HenrikBengtsson** [HCBravoLab/metagenomeSeq#32]
Hi, the metagenomeSeq package already imports [matrixStats](https://cran.r-project.org/package=matrixStats).  Would you mind making minor updates to it such that it also uses `matrixStats::rowMedians()`, because currently it uses `Biobase::rowMedians()`?  The latter is an outdated (still correct though) version and the one in matrixStats is faster and more up to date.

The changes are quite simple.  Your package uses `rowMedians()` in two place:
* [`cumNormStat()`](https://github.com/Bioconductor-mirror/metagenomeSeq/blob/17c90b8e254564bd6a99b29a588307ddab0bbf5e/R/cumNormStat.R#L48)
* [`cumNormStatFast()`](https://github.com/Bioconductor-mirror/metagenomeSeq/blob/17c90b8e254564bd6a99b29a588307ddab0bbf5e/R/cumNormStatFast.R#L42)

All that it takes is to replace the existing `rowMedians(abs(diffr),na.rm=TRUE)` with `matrixStats::rowMedians(abs(diffr),na.rm=TRUE)`.  FYI, unfortunately, you cannot just do `importFrom("matrixStats", "rowMedians")` because I think that will give a conflict with `import("Biobase")` that you're using.

The help/example _comment_ for [`aggregateBySample()`](https://github.com/Bioconductor-mirror/metagenomeSeq/blob/master/R/aggregateBySample.R#L22) should probably also mention this, but since it is a comment it doesn't really matter.

PS. I was about to fork https://github.com/HCBravoLab/metagenomeSeq and provide a PR, but I noticed it's out of date.

# Background
My reason for asking you for this small change is that I'd like to turn `matrixStats::rowMedians()` into a plain R function.  Currently it is an S4 method (which adds a bit of overhead when it comes to speed).  The reason for it being an S4 method is because `Biobase::rowMedians()` is an S4 method.  Changing the one on matrixStats may cause issues because of this, so the plan is to have the few packages (5 including yours) using `Biobase::rowMedians()` to switch to `matrixStats::rowMedians()`.  When no more packages are using `Biobase::rowMedians()`, then it is safe to turn `matrixStats::rowMedians()` into a plain function.  Eventually, `Biobase::rowMedians()` can follow, or even be deprecated.  For full details, see https://github.com/HenrikBengtsson/matrixStats/issues/80

**Comment by jnpaulson** [comment]
Thanks @HenrikBengtsson!
