### ISSUE TITLE
not allow covariates/confounders in fitFeatureModel()?

### ISSUE THREAD

**Issue by yijuanhu** [HCBravoLab/metagenomeSeq#50]
Hi,

It seems like the current version (1.18.0) of fitFeatureModel() does not allow any covariates/confounders to be adjusted. Am I correct? If true, is there any plan for an update?

Thanks,
Yijuan

**Comment by jnpaulson** [comment]
Thanks for checking in, that is correct. There is a plan for an update currently under works!

I'll close until we have that uploaded to the github.
