### ISSUE TITLE
coercion functions

### ISSUE THREAD

**Issue by lwaldron** [HCBravoLab/metagenomeSeq#53]
It would be useful to have coercion functions, to ExpressionSet and perhaps to SummarizedExperiment. See https://github.com/waldronlab/curatedMetagenomicData/issues/96.

**Comment by lwaldron** [comment]
FYI, it should be unnecessary for you to do anything here unless you think distinct coercion behavior is warranted; it will likely be taken care of at the `eSet` level: https://stat.ethz.ch/pipermail/bioc-devel/2017-September/011546.html

**Comment by hcorrada** [comment]
Excellent. Thanks!
