### ISSUE TITLE
fitZig Error 

### ISSUE THREAD

**Issue by ninaxhua** [HCBravoLab/metagenomeSeq#55]
Hello,
I'm trying to use fitZig since it can implement Limma's duplicateCorrelation function. I received this error when I ran: 
`fit_MRE = metagenomeSeq::fitZig(obj = n_paired_merged_MRE, mod = mod, useCSSoffset = FALSE, control = zigControl(), useMixedModel = TRUE, block = pData(n_paired_merged_MRE)$id)`

Error:
`it= 0, nll=232.25, log10(eps+1)=Inf, stillActive=1141
it= 1, nll=232.22, log10(eps+1)=Inf, stillActive=622
it= 2, nll=235.50, log10(eps+1)=Inf, stillActive=209
it= 3, nll=237.86, log10(eps+1)=Inf, stillActive=24
it= 4, nll=237.98, log10(eps+1)=Inf, stillActive=12
it= 5, nll=238.06, log10(eps+1)=Inf, stillActive=6
it= 6, nll=238.10, log10(eps+1)=Inf, stillActive=5
it= 7, nll=238.18, log10(eps+1)=Inf, stillActive=4
it= 8, nll=238.21, log10(eps+1)=Inf, stillActive=4
it= 9, nll=238.23, log10(eps+1)=Inf, stillActive=4
Error in if (abs(correlation) >= 1) stop("correlation is 1 or -1, so the model is degenerate") :
      missing value where TRUE/FALSE needed`

**Comment by jnpaulson** [comment]
Thanks - Can you provide an MRE? 

Best, 

On 2017-11-13 10:56, ninaxhua wrote: 

> Hello,
> I'm trying to use fitZig since it can implement Limma's duplicateCorrelation function. I received this error when I ran:
> fit_MRE = metagenomeSeq::fitZig(obj = n_paired_merged_MRE, mod = mod, useCSSoffset = FALSE, control = zigControl(), useMixedModel = TRUE, block = pData(n_paired_merged_MRE)$id) 
> 
> Error:
> it= 0, nll=232.25, log10(eps+1)=Inf, stillActive=1141 it= 1, nll=232.22, log10(eps+1)=Inf, stillActive=622 it= 2, nll=235.50, log10(eps+1)=Inf, stillActive=209 it= 3, nll=237.86, log10(eps+1)=Inf, stillActive=24 it= 4, nll=237.98, log10(eps+1)=Inf, stillActive=12 it= 5, nll=238.06, log10(eps+1)=Inf, stillActive=6 it= 6, nll=238.10, log10(eps+1)=Inf, stillActive=5 it= 7, nll=238.18, log10(eps+1)=Inf, stillActive=4 it= 8, nll=238.21, log10(eps+1)=Inf, stillActive=4 it= 9, nll=238.23, log10(eps+1)=Inf, stillActive=4 Error in if (abs(correlation) >= 1) stop("correlation is 1 or -1, so the model is degenerate") : missing value where TRUE/FALSE needed 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

  

Links:
------
[1] https://github.com/HCBravoLab/metagenomeSeq/issues/55
[2]

**Comment by ninaxhua** [comment]
[Link](https://drive.google.com/open?id=1T9aEQML4Y7mYk1JGrhXXxAXVYjaEPAKR) to drive folder. The object is called n_paired_merged_MRE.

**Comment by jnpaulson** [comment]
Hi Nina, 

Apologies this functionality is still under development. The output of the fitZig model does include a fitted MArrayLM object. From that object you can go ahead and use the duplicateCorrelation function.

**Comment by ninaxhua** [comment]
Hello,

So this is what I have so far
`fit_MRE = metagenomeSeq::fitZig(obj = n_paired_merged_MRE, mod = mod, useCSSoffset = FALSE, control = zigControl())
dupCor_MRE = duplicateCorrelation(fit_MRE$fit, mod, block = pData(n_paired_merged_MRE)$id)`

I got a data class error when using fit_MRE$fit as an object so I'm assuming I have to use one of these values as the object for duplicateCorrelation, but I'm not sure if I would use the coefficients matrix:
coefficients
stdev.unscaled
sigma
df.residual
cov.coefficients
pivot
rank
Amean
method
design
df
