### ISSUE TITLE
MetagenomeSeq fitZig issue

### ISSUE THREAD

**Issue by JingQiuyu** [HCBravoLab/metagenomeSeq#64]
when using fitZig function, after iteration, the stillActive=139, and the error message is as follows:
Error in if (df2[1] > 1e+06) fit$F.p.value <- pchisq(df1 * fit$F, df1,  : 
  missing value where TRUE/FALSE needed

the fitting arguments are as follows:
settings=zigControl(maxit=100,verbose=TRUE)
fit=fitZig(obj=test_V,mod=mod,useCSSoffset = FALSE,control = settings)

Does anyone know what happened here?

**Comment by jnpaulson** [comment]
Do you have all zeros in a few of your samples?

**Comment by JingQiuyu** [comment]
No, the count matrix is quite sparse. But for each sample, it's not all 0s.

**Comment by jnpaulson** [comment]
Feel free to email me an MRE and I’ll look into it.

**Comment by JingQiuyu** [comment]
Hi Joseph,

It’s hard for me to send you the MRexperiment. The attached is the matrix after CSS normalization, with each column as one sample, and each row as one species. There are two groups of sample.

Looking forward to your opinion about the issue.

Best,
Qiuyu

________________________________

**Comment by eam12** [comment]
Was this error ever solved? I'm currently getting the same error.

**Comment by hcorrada** [comment]
Please post your `sessionInfo()`

**Comment by eam12** [comment]
`sessionInfo()`
> R version 3.6.1 (2019-07-05)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 18362)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United States.1252 
> [2] LC_CTYPE=English_United States.1252   
> [3] LC_MONETARY=English_United States.1252
> [4] LC_NUMERIC=C                          
> [5] LC_TIME=English_United States.1252    
> 
> attached base packages:
> [1] parallel  stats     graphics  grDevices
> [5] utils     datasets  methods   base     
> 
> other attached packages:
>  [1] dplyr_0.8.3          reshape2_1.4.3      
>  [3] magrittr_1.5         phyloseq_1.28.0     
>  [5] ggplot2_3.2.1        metagenomeSeq_1.26.2
>  [7] RColorBrewer_1.1-2   glmnet_2.0-18       
>  [9] foreach_1.4.4        Matrix_1.2-17       
> [11] limma_3.40.5         Biobase_2.44.0      
> [13] BiocGenerics_0.30.0 
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.1         locfit_1.5-9.1    
>  [3] ape_5.3            lattice_0.20-38   
>  [5] gtools_3.8.1       IHW_1.12.0        
>  [7] Biostrings_2.52.0  digest_0.6.20     
>  [9] assertthat_0.2.1   slam_0.1-45       
> [11] R6_2.4.0           plyr_1.8.4        
> [13] stats4_3.6.1       pillar_1.4.2      
> [15] gplots_3.0.1.1     zlibbioc_1.30.0   
> [17] rlang_0.4.0        lazyeval_0.2.2    
> [19] gdata_2.18.0       rstudioapi_0.10   
> [21] data.table_1.12.2  vegan_2.5-5       
> [23] S4Vectors_0.22.0   labeling_0.3      
> [25] splines_3.6.1      stringr_1.4.0     
> [27] igraph_1.2.4.1     Wrench_1.2.0      
> [29] munsell_0.5.0      compiler_3.6.1    
> [31] xfun_0.8           pkgconfig_2.0.2   
> [33] multtest_2.40.0    mgcv_1.8-28       
> [35] biomformat_1.12.0  tidyselect_0.2.5  
> [37] tibble_2.1.3       IRanges_2.18.1    
> [39] codetools_0.2-16   matrixStats_0.54.0
> [41] permute_0.9-5      withr_2.1.2       
> [43] crayon_1.3.4       ggpubr_0.2.2      
> [45] bitops_1.0-6       MASS_7.3-51.4     
> [47] grid_3.6.1         nlme_3.1-140      
> [49] jsonlite_1.6       gtable_0.3.0      
> [51] scales_1.0.0       KernSmooth_2.23-15
> [53] stringi_1.4.3      XVector_0.24.0    
> [55] ggsignif_0.6.0     fdrtool_1.2.15    
> [57] lpsymphony_1.12.0  Rhdf5lib_1.6.0    
> [59] iterators_1.0.12   tools_3.6.1       
> [61] ade4_1.7-13        glue_1.3.1        
> [63] purrr_0.3.2        survival_2.44-1.1 
> [65] colorspace_1.4-1   rhdf5_2.28.0      
> [67] cluster_2.1.0      caTools_1.17.1.2  
> [69] knitr_1.24

**Comment by hcorrada** [comment]
Thanks. Can you provide a reproducible example that raises this error?

**Comment by eam12** [comment]
We figured out the issue. Thank you!

**Comment by hcorrada** [comment]
Wonderful! Let us know if we can be of further help.
