### ISSUE TITLE
Different results with cumNormMat and MRcounts(norm=TRUE)

### ISSUE THREAD

**Issue by alisimecn** [HCBravoLab/metagenomeSeq#69]
Hi !

I'm having an issue when trying to normalize my counts : I get a different matrix when I use cumNormMat(mydata, p=p) and when I use MRcounts(mydata, norm=TRUE, log=TRUE).

Here, mydata is an MRexperiment object obtained from a biom file.

Weirdly enough, I get the same matrix by doing MRcounts(mydata, norm=TRUE, log=TRUE) and MRcounts(cumNorm(mydata), norm=TRUE, log=TRUE).

Did I misunderstand the functions cumNormMat and MRcounts ? Are they not supposed to do the same thing ?

Thank you so much for your help,

Cheers !

**Comment by jnpaulson** [comment]
cumNormMat doesn't report log transformed counts, while MRcounts does.
You can log transform following cumNormMat

**Comment by alisimecn** [comment]
Oh, okay, thank you very much!
