### ISSUE TITLE
Build Failing with Release of Bioconductor 3.11

### ISSUE THREAD

**Issue by schifferl** [HCBravoLab/metagenomeSeq#75]
Hello, just wanted to let someone know that the package is failing with the new release of Bioconductor (3.11). My package, curatedMetagenomicData, fails too because metagenomeSeq fails. Thanks, Lucas

**Comment by hcorrada** [comment]
Thanks @schifferl. There is an depedency issue here (IHW->lpSymphony, lpSymphony is failing). I'll change our dependency to Suggests instead of Imports.
